/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_serialport_api_SerialPort */

#ifndef _Included_android_serialport_api_SerialPort
#define _Included_android_serialport_api_SerialPort
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     android_serialport_api_SerialPort
 * Method:    open
 * Signature: (Ljava/lang/String;II)Ljava/io/FileDescriptor;
 */
JNIEXPORT jobject JNICALL Java_android_1serialport_1api_SerialPort_open
        (JNIEnv *, jclass, jstring, jint, jboolean, jint);

/*
 * Class:     android_serialport_api_SerialPort
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_android_1serialport_1api_SerialPort_close
        (JNIEnv *, jobject);

JNIEXPORT void JNICALL Java_android_1serialport_1api_SerialPort_setParity
        (JNIEnv *env, jobject thiz, jint parity);

/*
 * Class:     com_example_serial_SerialPort
 * Method:    open
 * Signature: (Ljava/lang/String;II)Ljava/io/FileDescriptor;
 */
JNIEXPORT jobject JNICALL Java_com_example_serial_SerialPort_open
        (JNIEnv *, jclass, jstring, jint, jboolean, jint);

/*
 * Class:     com_example_serial_SerialPort
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_serial_SerialPort_close
        (JNIEnv *, jobject);

/*
 * Class:     com_example_serial_SerialPort
 * Method:    setParity
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_example_serial_SerialPort_setParity
        (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif


